using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using NpgsqlTypes;
using Pgvector;

namespace Assistant.Database;

[Index(nameof(AddedAtUtc))]
[Index(nameof(Context))]
[Index(nameof(IsStale))]
[Index(nameof(RelatedItemTableName), nameof(RelatedItemId), IsUnique = true)]
public class EmbeddingEntry
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; init; }

    public required DateTime AddedAtUtc { get; set; }

    public required EmbeddingContextKind Context { get; set; }

    public required string Content { get; set; }

    /// <summary>
    /// Generated by the database engine.
    /// </summary>
    public NpgsqlTsVector FullTextSearchVector { get; set; } = null!;

    [Column(TypeName = "vector(3072)")]
    [JsonIgnore]
    public Vector? Embedding { get; set; }

    public string? RelatedItemTableName { get; set; }

    public int? RelatedItemId { get; set; }

    public bool IsStale { get; set; }
}
